FROM golang:1.26-alpine

WORKDIR /app

RUN go install github.com/githubnemo/CompileDaemon@latest

# Copy go mod files
COPY go.mod  ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Expose port
EXPOSE 7678

# Use air for live reload
CMD ["CompileDaemon", "--build=go build -o main.o .", "--command=./main.o"]
