FROM golang:1.24-alpine

WORKDIR /app

RUN go install github.com/githubnemo/CompileDaemon@latest

# Copy go mod files
COPY go.mod  ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

RUN mkdir -p /app/store

# Expose port
EXPOSE 8280

# Use air for live reload
CMD ["CompileDaemon", "--build=go build -o main.o .", "--command=./main.o"]